# Generated by Django 4.0.5 on 2022-07-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
